version: 2
orbs:
  twilio: circleci/twilio@0.0.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip

      - run:
          name: "Create Environment file"
          command: |
            mv .env.example .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # prepare the database
      - run:
          name: "Generate app key"
          command: php artisan key:generate


      # run tests with phpunit
      - run:
          name: "Run Tests"
          command: composer test
          - twilio/sendsms:
              body: Send SMS to Twilio phone number for successful build
          - twilio/alert:
              body: Send SMS to Twilio phone number for failed build

